import os
from dydx3.constants import API_HOST_SEPOLIA, API_HOST_MAINNET
from dotenv import load_dotenv, dotenv_values
config = dotenv_values("../.env")
load_dotenv()

# SELECT MODE#
MODE = "DEVELOPMENT"

# Close all open positions and orders
ABORT_ALL_POSITIONS = True

# Find Cointegrated pairs
FIND_COINTEGRATED = True

# Manage Exits
MANAGE_EXITS = True

# Place Trades
PLACE_TRADES = True

# Resolution
RESOLUTION = "1HOUR"

# Stats Window
WINDOW = 21

# Thresholds - Openng
MAX_HALF_LIFE = 24
ZSCORE_THRESH = 1.5
USD_PER_TRADE = 50
USD_MIN_COLLATERAL = 1880

# THRESHOLDS - Closing
CLOSE_AT_ZSCORE_CROSS = True

ETHEREUM_ADDRESS = "0x0f2E43eD03Eba1Cbda3758b0cbA538E3Be168EBC"
ETH_PRIVATE_KEY = os.getenv("ETH_PRIVATE_KEY")

# KEYS PRODUCTION
# Must remember to be on mainnet on DYDX
STARK_PRIVATE_KEY_MAINNET = os.getenv("STARK_PRIVATE_KEY_MAINNET")
DYDX_API_KEY_MAINNET = os.getenv("STARK_PRIVATE_KEY_MAINNET")
DYDX_API_SECRET_MAINNET = os.getenv("DYDX_API_SECRET_MAINNET")
DYDX_API_PASSPHRASE_MAINNET = os.getenv("DYDX_API_PASSPHRASE_MAINNET")

# KEYS DEVELOPMENT
# Must be on testnet on dydx
STARK_PRIVATE_KEY_TESTNET = os.getenv("STARK_PRIVATE_KEY_TESTNET")
DYDX_API_KEY_TESTNET = os.getenv("DYDX_API_KEY_TESTNET")
DYDX_API_SECRET_TESTNET = os.getenv("DYDX_API_SECRET_TESTNET")
DYDX_API_PASSPHRASE_TESTNET = os.getenv("DYDX_API_PASSPHRASE_TESTNET")

# KEYS - Export
STARK_PRIVATE_KEY = STARK_PRIVATE_KEY_MAINNET if MODE == "Production" else STARK_PRIVATE_KEY_TESTNET
DYDX_API_KEY = DYDX_API_KEY_MAINNET if MODE == "Production" else DYDX_API_KEY_TESTNET
DYDX_API_SECRET = DYDX_API_SECRET_MAINNET if MODE == "Production" else DYDX_API_SECRET_TESTNET
DYDX_API_PASSPHRASE = DYDX_API_PASSPHRASE_MAINNET if MODE == "Production" else DYDX_API_PASSPHRASE_TESTNET

# HOST - Export
HOST = API_HOST_MAINNET if MODE == "Production" else API_HOST_SEPOLIA

# HTTP PROVIDER
HTTP_PROVIDER_MAINNET = ""
HTTP_PROVIDER_TESTNET = "https://eth-sepolia.g.alchemy.com/v2/xMlzt5PxkxG2inTvEAPHWzjL0Ogk0JUo"
HTTP_PROVIDER = HTTP_PROVIDER_MAINNET if MODE == "Production" else HTTP_PROVIDER_TESTNET